version: '3'
services:
  web:
    container_name: web
    image: "shortener_url:latest"
    command: npm start
    ports:
      - "3000:3000"
    links:
      - redis
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
     - NODE_ENV=production
     - APP_PORT=3000
     - APP_URL=http://link.cogati.com
     - REDIS_PORT=6379
     - REDIS_HOST=redis
  redis:
    container_name: redis
    image: "redis:alpine"
    ports:
      - "6379:6379"
    deploy:
      resources:
        limits:
          cpus: '0.30'
          memory: 1M
        reservations:
          cpus: '0.10'
          memory: 1M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
  webserver:
    image: nginx:mainline-alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./scripts/nginx-conf:/etc/nginx/conf.d
    depends_on:
      - web