version: '3'

services:

  web1:
    restart: always
    environment:
     - NODE_ENV=production
     - APP_PORT=3000
     - APP_URL=https://link.cogati.com
     - REDIS_PORT=6379
     - REDIS_HOST=redis

  web2:
    restart: always
    environment:
     - NODE_ENV=production
     - APP_PORT=3000
     - APP_URL=https://link.cogati.com
     - REDIS_PORT=6379
     - REDIS_HOST=redis

  web3:
    restart: always
    environment:
     - NODE_ENV=production
     - APP_PORT=3000
     - APP_URL=https://link.cogati.com
     - REDIS_PORT=6379
     - REDIS_HOST=redis

  redis:
    restart: always
    

  webserver:
    image: nginx:1.15-alpine
    container_name: webserver
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./scripts/nginx-conf:/etc/nginx/conf.d
      - ./scripts/certbot/conf:/etc/letsencrypt
      - ./scripts/certbot/www:/var/www/certbot
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  certbot:
    container_name: certbot
    image: certbot/certbot
    restart: always
    volumes:
      - ./scripts/certbot/conf:/etc/letsencrypt
      - ./scripts/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
