version: '3'
services:
  web:
    container_name: web
    image: "shortener_url:latest"
    command: npm start
    ports:
      - "3000:3000"
    links:
      - redis
    environment:
     - NODE_ENV=production
     - APP_PORT=3000
     - REDIS_PORT=6379
     - REDIS_HOST=redis
  redis:
    container_name: redis
    image: "redis:alpine"
    ports:
      - "6379:6379"