version: '3'

services:

  web:
    image: yudapc/shortener_url:0.0.1
    command: npm start
    ports:
      - "3000-3002:3000"
    links:
      - redis
    depends_on:
      - redis

  redis:
    hostname: redis
    image: redis:4.0.5-alpine
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - ./data:/data
    ports:
      - "6379:6379"


