version: '3'

services:

  web:
    container_name: web
    image: "shortener_url:latest"
    command: npm start
    ports:
      - "3000:3000"
    links:
      - redis
    depends_on:
      - redis
    
  redis:
    container_name: redis
    hostname: redis
    image: redis:4.0.5-alpine
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - ./data:/data
    ports:
      - "6379:6379"
    
   